version: '1.0.0'
services:
  fastapi:
    build: ./fastapi-app
    ports:
      - "8001:8001"
    depends_on:
      - redis
    volumes:
      - app_data:/app/app/data

  reactjs:
    build: ./react-app
    ports:
      - "3000:3000"
    depends_on:
      - fastapi

  celery:
    build: ./fastapi-app
    command: celery -A app.celery_worker worker --loglevel=info
    volumes:
      - app_data:/app/app/data
    depends_on:
      - redis
      - fastapi

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  flower:
    build: ./fastapi-app
    environment:
      -  CELERY_BROKER_URL redis://redis:6379/0
      -  CELERY_RESULT_BACKEND redis://redis:6379/0
    command: celery -A app.celery_worker flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery

volumes:
  app_data:
